config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  resources :wines, only: [:show, :index] do
    resources :user_ratings, only: [:create]
    collection do
      get 'closed', to: "wines#closed"
      get 'all', to: "wines#all"
      get 'nowine', to: "wines#nowine"
    end
  end

  resources :user_answers, only: [:create]

  get '/questions', to: 'pages#questions', as: 'questions'
  post '/questions', to: 'pages#wines_filtering', as: 'wines_filtering'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_card.html.erb
<div class="col-xs-12">
  <div class="wine-card">
    <div class="card-title">
      <% if wine[:wine].name.length > 30 %>
        <%= wine[:wine].name.split("").first(25).join("") %>
        <span style="font-weight:100;">...</span>
      <% else %>
        <%= wine[:wine].name %>
      <% end %>
    </div>
    <div class="card-header">
      <div class="card-header-side">
        <div class="card-kpis">
          <div class="card-kpis-container">
            <div class="card-kpi card-kpi-price card-kpi-green">
              <div class="kpi-picto">
                <div class="font-awesome-circled">
                  <i class="fa fa-eur" style="font-size: 27px;"></i>
                </div>
              </div>
              <div class="kpi-text">
                <%= wine[:wine].price.round %>€
              </div>
            </div>
            <hr/>
            <div class="card-kpi card-kpi-distance card-kpi-red">
              <div class="kpi-picto">
                <div class="font-awesome-circled">
                  <i class="fa fa-map-marker" style="font-size:30px;"></i>
                </div>
              </div>
              <div class="kpi-text">
                <%= wine[:info_store][:distance] %>m
              </div>
            </div>
            <hr/>
            <div class="card-kpi card-kpi-rating card-kpi-green">
              <div class="kpi-picto">
                <div class="font-awesome-circled">
                  <i class="fa fa-heart"></i>
                </div>
              </div>
              <div class="kpi-text">
                <% if wine[:wine].external_ratings.last.nil? %>
                  'not rated'
                <% else %>
                  <%= wine[:wine].external_ratings.last.avg_rating.to_s.gsub(".",",") %>
                  <span style="font-size: 12px;"> /5</span>
                <% end %>
              </div>
            </div>
            <div class="media-query-500">
              <hr/>
              <div class="card-kpi">
                <div class="kpi-text kpi-overall">
                  <span style="font-size: 23px;"><%= wine[:score].round %>%</span>
                  <div class="media" style="line-height: 1; color: #EFEFEF;">WINE</div>
                  <div class="media" style="font-size: 34px; line-height: 1.1;">FIT</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-header-side">
    <div class="card-header-side bottle-image"
      style="background-image:url(<%= wine[:wine].photo %>);
              background-repeat: no-repeat;
              background-position: center;
              background-size: cover;">
    </div>
      </div>
    </div>

    <%= link_to "GO GET IT", wine_path(wine[:wine], store_id: wine[:info_store][:store].id,latitude: @latitude, longitude: @longitude), :class => "button-submit"  %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_loader.html.erb
<div class="spinner centered bg-alizarin text-center flex-center">
  <i class="fa fa-spinner fa-pulse fa-5x"></i>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_new.html.erb
<div class="navbar-new">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
        <% end %>
  <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path %>
  <% end %>
</div>