config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  resources :wines, only: [:show, :index] do
    resources :user_ratings, only: [:create]
    collection do
      get 'closed', to: "wines#closed"
      get 'all', to: "wines#all"
      get 'nowine', to: "wines#nowine"
    end
  end

  resources :user_answers, only: [:create]

  get '/questions', to: 'pages#questions', as: 'questions'
  post '/questions', to: 'pages#wines_filtering', as: 'wines_filtering'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/pages/home.html.erb
<div class="centered bg-alizarin text-center flex-center">
  <div class="wrapper-home">
    <%= link_to(questions_path) do %>
      <%= image_tag("logo_hello_wine.png",class: "hatch")  %> <!-- class: "pulse" -->
    <% end %>
    <div class="title-lato">
    <span class="increment">
    </span> wines around you
    <br>
    <div>which one is the best ?</div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    i = 1

    var interval = setInterval(function() {
      $('.increment').html(i)
      if(i === <%= @wine_count %>) {
        clearInterval(interval)
      }
      i ++
    }, 1)
  </script>
<% end %>

app/views/pages/questions.html.erb
<%= react_component "Questions",
  questions: [
    {
      topic: "color",
      question: "What do you wanna drink ?",
      pic_url: asset_url("pic_color.png"),
      answers: [ "Red Wine", "White Wine", "Rosé Wine" ],
      values: [ "red", "white", "pink"]
    },
    {
      topic: "meal",
      question: "What do you gonna eat ?",
      pic_url: asset_url("pic_meal.png"),
      answers: [ "Huge meat plate", "Bob the fish", "Piece of tofu" ],
      values: [ "viande", "poisson", "vegie"]
    },
    {
      topic: "price",
      question: "What's your budget ?",
      pic_url: asset_url("pic_price.png"),
      answers: [ "Less than 10€", "From 10 to 20€", "More than 20€" ],
      values: [ "less-10", "10-20", "more-20"]
    }]
%>