config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'

  resources :wines, only: [:show, :index] do
    resources :user_ratings, only: [:create]
    collection do
      get 'closed', to: "wines#closed"
      get 'all', to: "wines#all"
      get 'nowine', to: "wines#nowine"
    end
  end

  resources :user_answers, only: [:create]

  get '/questions', to: 'pages#questions', as: 'questions'
  post '/questions', to: 'pages#wines_filtering', as: 'wines_filtering'

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :brand

  has_many :external_ratings, dependent: :destroy
  has_many :user_ratings,     dependent: :destroy

  mount_uploader :photo, PhotoUploader

  scope :filter_by_location, -> (latitude, longitude) do
    stores = Store.near([latitude, longitude], 1, units: :km)
    #stores = stores.joins(:store_schedules).where("start_am <= ? AND end_pm >= ? AND day = ?", Time.now, Time.now, Date.today.cwday)

    distinct.joins(brand: :stores).where(stores: { id: stores.map(&:id) })# map { |x| x.id }
  end
   #SELECT DISTINCT "wines".* FROM "wines"
    #INNER JOIN "brands" ON "brands"."id" = "wines"."brand_id"
    #INNER JOIN "stores" ON "stores"."brand_id" = "brands"."id"
    #WHERE "stores"."id" IN (4615, 4589, 4666, 4692)

  scope :filter_by_external_ratings, -> do
    joins(:external_ratings)
  end

  scope :filter_by_color, -> (color) { where(color: color) }

  scope :filter_by_pairing, -> (pairing) do
    condition = <<~HEREDOC
      (wines.pairing_1 IS NULL OR wines.pairing_1 = :pairing)
      OR wines.pairing_2 = :pairing
      OR wines.pairing_3 = :pairing
      OR wines.pairing_4 = :pairing
      OR wines.pairing_5 = :pairing
    HEREDOC

    where(condition, pairing: pairing)
  end

  scope :filter_by_price, -> (price) do
    case price
    when 'less-10'
      where('wines.price <= 10')
    when '10-20'
      where('wines.price >= 10 AND wines.price <= 20')
    when 'more-20'
      where('wines.price >= 20')
    end
  end

  def nearest(latitude,longitude)
    stores_closed = []
    stores = Store.all
    Brand.all.each do |brand|
      #stores = stores.filter_by_opening(brand.id)
      unless stores.empty?
        store = brand.stores.near([latitude, longitude], 1, units: :km, :order => "distance").first
        stores_closed << {
          store: store,
          distance: (Geocoder::Calculations.distance_between([latitude,longitude], store, {units: :km}) * 1000).round
        }
      end
    end
    stores_closed.sort_by! { |hash| hash[:distance]}
    selected_store = stores_closed.first
  end

  def self.find_wines(latitude,longitude,color,price,pairing)
    wine_list = Wine.all
    puts "START FIND WINES"
    #All wines whitch have an external rating
    wine_list = wine_list.filter_by_external_ratings
    return 1 if wine_list.count == 0
    puts "SCOPE EXT RATING"
    puts wine_list.count
    #All the wines in store less than 1km
    wine_list = wine_list.filter_by_location(latitude, longitude)
    return 2 if wine_list.count == 0
    puts "SCOPE LOCATION"
    puts wine_list.count
    #Filter color
    wine_list = wine_list.filter_by_color(color) unless color.nil?
    return 3 if wine_list.count == 0
    puts "SCOPE COLOR"
    puts wine_list.count
    #Filter price
    wine_list = wine_list.filter_by_price(price) unless price.nil?
    return 4 if wine_list.count == 0
    puts "SCOPE PRICE"
    puts wine_list.count

    #Filter pairing
    wine_list = wine_list.filter_by_pairing(pairing) unless pairing.nil?
    return 5 if wine_list.count == 0
     puts "SCOPE PAIRING"
     puts wine_list.count

    return wine_list
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :all, :closed, :nowine]

  def all
    @wines = Wine.all
  end

  def index
    puts "CONTROLLER ENTRANCE"
    puts @latitude = params[:latitude]
    puts @longitude = params[:longitude]
    @skip_navbard = true
    @get_loader = true

    @wines = Wine.find_wines(@latitude,@longitude,params[:color],params[:price],params[:pairing])
    puts "END FIND WINES"
    puts "1er vin sortir find wines"

    if @wines == 1 || @wines == 3 || @wines == 4 || @wines == 5
      redirect_to nowine_wines_path
    elsif @wines == 2
      redirect_to closed_wines_path
    else
      puts @wines.first
      @wines = wine_sorting(@wines, @latitude, @longitude) unless @latitude == "undefined" || @longitude == "undefined"
      puts "END WINE SORTING"
      puts @wines.first
      @wines = @wines.first(10)
    end

  end

  def show
    @wine = Wine.find(params[:id])
    @store = Store.find(params[:store_id])
    @store_closed =  @store.store_schedules.where(day: Date.today.cwday).first[:end_pm]
    @store_closed = Time.now.change({ hour: @store_closed.hour, min: @store_closed.min })

    if @store.nil?
      redirect_to closed_wines_path
    else

      # Let's DYNAMICALLY build the markers for the view.
      @markers = Gmaps4rails.build_markers(@stores) do |store, marker|
        marker.lat store.latitude
        marker.lng store.longitude
      end

    end
  end

  private

  def wine_sorting(wines,latitude,longitude)
    wines_matrix = []
    weight_rating = 0.9
    weight_distance = 0.1
    puts "WINE SORTING"
    wines.each do |wine|

      unless wine.external_ratings.first.nil?
        info_store = wine.nearest(latitude,longitude)
        puts "info store"
        puts info_store
        rating_score = wine.external_ratings.last.avg_rating * 20 * weight_rating
        distance_score = distance_note( info_store[:distance] ) * weight_distance

        puts "rating_score"
        puts rating_score

        puts "distance_score"
        puts distance_score

        if rating_score.nil?
          score = 0
        else
          score = (rating_score + distance_score).round
        end
        wines_matrix << { wine: wine, score: score, info_store: info_store } unless wine.photo == "null"
      end
    end
    puts "wine wines_matrix"
    puts wines_matrix.count
    @wines = wines_matrix.sort { | a, b | b[:score] <=> a[:score] }

  end

  def distance_note(distance)
    if distance <= 50
      return 100
    elsif distance > 50 && distance <= 500
      return -( 1.to_f / 9 ) * (distance + 50) + 100
    elsif distance > 500 && distance <= 600
      return - ( 1.to_f / 2 ) * distance + 300
    else
      return 0
    end

  end

end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/closed.html.erb
<div class="closed-style">
  <div class="text-center padded-2">
  <%= image_tag("wine_oclock.png", size: "170x232", alt: "Wine Oclock") %>

    <h1>Sorry, all the shops are closed</h1>
    <%= link_to "Back", wines_path, {class: "btn btn-closed-stores"} %>
  </div>
</div>

app/views/wines/index.html.erb
<div class="wine-cards">
<%= react_component "WineCards",
          render(template: 'wines/index.json.jbuilder') %>
</div>

app/views/wines/nowine.html.erb
<div class="centered bg-grey text-center flex-center closed-style">
  <div class="text-center padded-2">
    <h1> No wines around you. What about water ?</h2>
    <%= link_to 'Try again later', "/" ,anchor: "#" %>
  </div>
</div>

app/views/wines/show.html.erb
<% content_for :meta_title, "Retrouvez le chemin le plus court entre le #{@wine.name} et vous !" %>
<% content_for :meta_image, @wine.photo.url %>
<div class='overflow-hidden'>

  <div class="wrapper-transparent wrapper-margin-down">
    <div class="wrappe-head">
      <div class="btn-list">
        <%= link_to '< Back', :back ,anchor: "##wine-{@wine.id}" %>
      </div>
      <div class="title-show text-center">
        <h3 class="wine-name"><%= @wine.name.split("").first(40).join("") %></h3>
        <h4 class="wine-appelation"><%= @wine.appellation %></h4>
      </div>
    </div>

      <div class="wrapper-info-wine">
          <div class="wine-info">
            <div class="font-awesome-show-circled text-center">
              <span class="fa fa-map-marker fa-2x wine-details"></span>
            </div>
              <span class="fa-show"><%= @wine.region %></span>
          </div>
          <div class="wine-info">
            <div class="font-awesome-show-circled text-center">
              <span class="fa fa-percent fa-2x wine-details"></span>
            </div>
              <span class="fa-show"><%= @wine.alcohol_percent %> alc</span>
          </div>
          <div class="wine-info">
            <div class="font-awesome-show-circled text-center">
              <span class="fa fa-euro fa-2x wine-details"></span>
            </div>
              <span class="fa-show"><%= @wine.price %> €</span>
          </div>
          <div class="wine-info">
            <div class="font-awesome-show-circled text-center">
              <span class="fa fa-shopping-cart fa-2x wine-details"></span>
            </div>
              <span class="fa-show"><%= @wine.brand.name %></span>
          </div>
          <div class="wine-info flex-1">
            <div class="font-awesome-show-circled text-center">
              <span class="fa fa-clock-o fa-2x wine-details"></span>
            </div>
              <span class="fa-show">Close in <%= distance_of_time_in_words_to_now(@store_closed) %></span>
          </div>
      </div>

    <div class="card-map-wine-image-container img-show">
      <%= image_tag(@wine.photo) %>
    </div>

  </div>

  <div id="map-show" class="map-margin-up">
    <div id="map-filter" class="map-filter-closed"></div>
    <div id="map" style="width: 100%; height: 100vh;"></div>
  </div>

  <div id= "btn-closed" class="text-center hidden">
    <i class="fa fa-times-circle fa-3x"></i>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {

      function buildMap() {
        handler = Gmaps.build('Google');
        handler.buildMap({provider: { scrollwheel: false }, internal: { id: 'map' } }, function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if(navigator.geolocation)
            navigator.geolocation.getCurrentPosition(displayOnMap);
          calcRoute();
          directionsDisplay.setMap(handler.getMap());
        });
      }

      buildMap();


      function displayOnMap(position){
        var marker = handler.addMarker({
          lat: position.coords.latitude,
          lng: position.coords.longitude
        });
       <!--  handler.map.centerOn(marker); -->
      };

      var directionsDisplay = new google.maps.DirectionsRenderer();
      var directionsService = new google.maps.DirectionsService();

      function calcRoute() {

        var origin      = new google.maps.LatLng(<%= params[:latitude] %>, <%= params[:longitude] %>);
        var destination = new google.maps.LatLng(<%= @store.latitude %>, <%= @store.longitude %>);
        var request = {
            origin:      origin,
            destination: destination,
            travelMode:  google.maps.TravelMode.WALKING
        };
        directionsService.route(request, function(response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
          }
        });
      }

      $("#map-show").on("click", function() {
        $(this).removeClass('map-margin-up').addClass('map-margin-down');

        $('.wrapper-transparent').removeClass('wrapper-margin-down').addClass('wrapper-margin-up');
        $("#btn-closed").removeClass('hidden')
        $(".map-filter-closed").slideUp( 400,function(){
          <!-- $('.img-show').hide("slow"); -->
         <!--  $('.card-map-wine-image-container').css('background-color','$alazarin'); -->

        });

      });
      $("#btn-closed").on("click", function() {
        $("#map-show").removeClass('map-margin-down').addClass('map-margin-up');
        $("#btn-closed").addClass('hidden');
        $('.wrapper-transparent').addClass('wrapper-margin-down').removeClass('wrapper-margin-up');
        $(".map-filter-closed").slideDown( 400,function(){
         <!--  $('.card-map-wine-image-container').css('background-color','white'); -->
          <!-- $('.img-show').show("slow"); -->
        });

      });
    });
  <% end %>
<% end %>